apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: react-k8-container
        image: ganesh2soft/my-react-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
            