apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  ports:
    - protocol: TCP
      port: 80      # Port exposed on the Service
      targetPort: 80  # Port the container is listening on
      nodePort: 30007
